In [48]:
import numpy as np
import pandas as pd

RNAseq_data = open('/Users/rl884/Downloads/PICIN/Data/isolated_subnetwork_5/RNAseq_full.txt', 'r')
StableStatesCollector = {}
TranscriptionPofiles = []
for line in RNAseq_data:
    line_split = line.split()
    if line_split[0] == 'ABF1':
        continue
    else:
        for i in range(0, len(line_split)):
            line_split[i] = 100*float(line_split[i])
    TranscriptionPofiles.append(line_split[1:])
    StableStatesCollector[str(line_split[1:])] = 1

TranscriptionPofiles = np.array(TranscriptionPofiles)
TranscriptionPofileMax = np.max(TranscriptionPofiles, axis=0)

TransMaxOver1 = []
for each in TranscriptionPofileMax:
    TransMaxOver1.append(1/each)

VectorCollector = []
FreqCollector = []
for keys in StableStatesCollector:
    if StableStatesCollector[keys] >= 0: # Threshold for the Stable States frequency
        VectorCollector.append(keys)
        FreqCollector.append(StableStatesCollector[keys])
    else:
        pass
for i in range(0, len(VectorCollector)):
    VectorCollector[i] = VectorCollector[i][:-1]
    VectorCollector[i] = VectorCollector[i][1:]
MatrixCollector = np.random.randint(2,size=(1, len(VectorCollector), len(VectorCollector[0].split())))[0]
for i in range(0, len(VectorCollector)):
    TempVec = VectorCollector[i].split()
    for j in range(0, len(TempVec)):
        MatrixCollector[i][j] = float(TempVec[j][0:-1])

MyCounter = 0
StableStateThreshold = 0.3
#print(len(MatrixCollector))
while MyCounter < MatrixCollector.shape[0] - 1:
    j = MyCounter + 1
    if MyCounter == MatrixCollector.shape[0] - 1 - 1:
        #print(np.dot(abs(MatrixCollector[MyCounter] - MatrixCollector[j]), TransMaxOver1))
        if np.dot(abs(MatrixCollector[MyCounter] - MatrixCollector[j]), TransMaxOver1) < StableStateThreshold:
            print(MatrixCollector[MyCounter], '\n', MatrixCollector[j], '\n', np.dot(abs(MatrixCollector[MyCounter] - MatrixCollector[j]), TransMaxOver1), '\n\n')
            TempCombineVector = (MatrixCollector[MyCounter] + MatrixCollector[j]) * 0.5
            MatrixCollector[MyCounter] = TempCombineVector
            MatrixCollector = np.delete(MatrixCollector, j, axis = 0)
            TempCombineFreq = FreqCollector[MyCounter] + FreqCollector[j]
            FreqCollector[MyCounter] = TempCombineFreq
            FreqCollector.pop(j)
        else:
            pass
        break
    else:
        while True:
            if np.dot(abs(MatrixCollector[MyCounter] - MatrixCollector[j]), TransMaxOver1) < StableStateThreshold:
                print(MatrixCollector[MyCounter], '\n', MatrixCollector[j], '\n', np.dot(abs(MatrixCollector[MyCounter] - MatrixCollector[j]), TransMaxOver1), '\n\n')
                TempCombineVector = (MatrixCollector[MyCounter] + MatrixCollector[j]) * 0.5
                MatrixCollector[MyCounter] = TempCombineVector
                MatrixCollector = np.delete(MatrixCollector, j, axis = 0)
                TempCombineFreq = FreqCollector[MyCounter] + FreqCollector[j]
                FreqCollector[MyCounter] = TempCombineFreq
                FreqCollector.pop(j)
                break
            else:
                j = j + 1
            if j == MatrixCollector.shape[0]:
                MyCounter = MyCounter + 1
                break
            else:
                pass

#print(StableStatesCollector)

for i in range(0, len(MatrixCollector)):
    print(str(MatrixCollector[i]))
print(len(MatrixCollector))

outfile = open('/Users/rl884/Downloads/PICIN/test_3.txt', 'a')
for each in MatrixCollector:
    if len(np.argwhere(each == 0)) == 0:
           outfile.write('-1\t')
    else:
           outfile.write(str(np.argwhere(each == 0)[0][0])+'\t')
    for values in each:
           outfile.write(str(values)+'\t')
    outfile.write('\n')
outfile.close()

[245 261 236 166 190 167 166 177] 
 [249 250 241 214 196 184 182 187] 
 0.23054917323867713 


[247 255 238 190 193 175 174 182] 
 [242 181 221 189 198 177 182 292] 
 0.2903163873478347 


[244 218 229 189 195 176 178 237] 
 [229 218 213 246 195 196 214 213] 
 0.28614202164376806 


[236 218 221 217 195 186 196 225] 
 [208 224 212 225 197 205 191 194] 
 0.19300826608634075 


[222 221 216 221 196 195 193 209] 
 [225 187 177 192 198 201 185 168] 
 0.24333346782882753 


[223 204 196 206 197 198 189 188] 
 [182 191 204 179 199 186 206 190] 
 0.25527404730689757 


[202 197 200 192 198 192 197 189] 
 [185 182 192 188 191 207 201 192] 
 0.1759746228378621 


[193 189 196 190 194 199 199 190] 
 [172 205 187 234 193 210 243 183] 
 0.28886509938412613 


[182 197 191 212 193 204 221 186] 
 [140 187 188 209 201 184 247 177] 
 0.27367136950453347 


[161 192 189 210 197 194 234 181] 
 [189 195 206 227 198 213 205 202] 
 0.24657785083232786 


[175 193 197 218 197 203 219 191] 
 [220 192 201 170

In [62]:
eval('[1,2,3,4]')

[1, 2, 3, 4]

In [71]:
A = [[118.00023607034429, 118.00026606011741, 118.0002061319883, 118.00026605397953, 118.00026563672574, 118.00023678059742, 118.00026625876163, 118.00000000008046], [999.1093185125633, 118.0002660601165, 118.0002058330079, 118.00026605398384, 999.1095843407426, 118.00023673432446, 118.00026617739421, 118.00000000008035], [118.00023650503837, 999.1099108710029, 118.00020577384035, 118.00026606011104, 118.00026606734802, 118.00023676052125, 118.00026619744963, 118.00026579161063], [999.1093698280638, 999.1099110597595, 118.00020599625198, 118.00026606011109, 999.1096356494476, 118.0002369328985, 118.0002663994355, 118.00026579161076], [118.00023629119576, 118.00026606011745, 999.1093839255558, 118.00026605397125, 118.00026585528923, 20.09892780657865, 118.00000000000365, 118.00000000008043], [999.107500850335, 118.00026606010508, 999.1083738523005, 118.00026605412202, 999.1077667214367, 20.09904003695243, 118.00000000000364, 118.00000000008035], [118.00023650776143, 999.1099132272811, 999.1091034436529, 118.00026606011065, 118.00026607007139, 20.098958971241174, 118.00000000000367, 118.00026579161096], [999.1092978007193, 999.1099134607855, 999.10919506956, 118.00026606009658, 999.1095636222358, 20.098948790563462, 118.00000000000364, 118.00026579159706], [118.0002360202866, 118.00026606011684, 20.00009999500748, 118.00026605398858, 118.00026558626837, 999.109484088324, 999.1094840883277, 118.00000000008043], [999.1077900049448, 118.00026606011195, 20.00009980770797, 118.00026605404375, 999.1080558556196, 999.1099003702069, 999.1099003702105, 118.00000000008035], [118.00023694146967, 999.1098952172267, 20.00009982453348, 118.00026606007815, 118.00026650388097, 999.1098052176632, 999.1098052176667, 118.00026579157304], [999.1087300944147, 999.1098981164794, 20.000100357840946, 118.00026605951656, 999.1089959188555, 999.1075567588027, 999.1075567588064, 118.00026579101302], [20.098907224023115, 999.1099126282033, 118.0002062243209, 999.1016738142905, 118.000000000004, 118.00023674858676, 118.00026623641925, 998.2124930057396], [20.09890686471796, 999.109914646624, 999.1089141097934, 999.101679107244, 118.00000000000381, 20.098980008343318, 118.00000000000367, 998.2125003097282], [20.098908231548812, 999.109909919635, 20.000100204693886, 999.1016616697107, 118.0000000000039, 999.1083717986726, 999.1083717986764, 998.2124781675328]]
A = [[118.00023630254904, 118.00026606011755, 118.00020607474701, 118.00026605396991, 118.00026586622238, 118.00023714150538, 118.00026662212265, 118.00000000008043], [999.1094333806083, 118.0002660601169, 118.0002063349874, 118.000266053975, 999.1096992057928, 118.00023685853296, 118.00026636170772, 118.00000000008035], [118.00023653704133, 999.109910751393, 118.00020606770529, 118.00026606011114, 118.00026609935026, 118.00023668864114, 118.00026615712949, 118.0002657916107], [999.1093508674494, 999.1099124409636, 118.00020589204613, 118.0002660601113, 999.109616688827, 118.00023694952691, 118.00026640461198, 118.00026579161138], [118.00023623764648, 118.00026606011741, 999.1091005417744, 118.0002660539736, 118.00026580222197, 20.09895929367348, 118.00000000000364, 118.00000000008043], [999.1058143066354, 118.00026606009386, 999.1094449834859, 118.00026605425779, 999.1060802190968, 20.098921022328128, 118.00000000000358, 118.00000000008035], [118.0002364968579, 999.109913469636, 999.1091874815856, 118.00026606011038, 118.00026605916835, 20.098949633690616, 118.00000000000365, 118.00026579161073], [999.1096303010656, 999.1099140825254, 999.1093115850119, 118.00026606009996, 999.1098961225687, 20.098935844403528, 118.00000000000365, 118.00026579160067], [118.00023533683765, 118.00026606011691, 20.000099809933175, 118.00026605399708, 118.0002649071142, 999.1098953699397, 999.1098953699434, 118.00000000008043], [999.1078002675408, 118.00026606010871, 20.00009981239461, 118.00026605408067, 999.1080661272341, 999.1098762716881, 999.1098762716915, 118.00000000008035], [118.0002364405318, 999.1099030745916, 20.00009982177834, 118.00026606008399, 118.00026600292277, 999.1098201160073, 999.1098201160108, 118.00026579158126], [999.1078674566731, 999.1098895001182, 20.000099937049267, 118.00026605900777, 999.1081332841977, 999.109230704528, 999.1092307045317, 118.0002657905022], [20.098909345701337, 999.1099021187124, 118.00020427082099, 999.1016439284092, 118.00000000000401, 118.00023730588308, 118.00026658615562, 998.2124526512387], [20.098906758605864, 999.1099148829874, 999.1093971905614, 999.1016803081824, 118.00000000000385, 20.09892633268828, 118.00000000000367, 998.2125017455774], [20.098911157641396, 999.1098951612684, 20.000099881581693, 999.1016191416527, 118.00000000000404, 999.1094860947619, 999.1094860947654, 998.2124209388911]]
print(np.min(A,axis=0))
outfile = open('/Users/rl884/Downloads/Gold_Standard.txt', 'a')
for each in A:
    for values in each:
        outfile.write(str(values)+'\t')
    outfile.write('\n')
outfile.close()

[ 20.09890676 118.00026606  20.00009981 118.00026605 118.
  20.09892102 118.         118.        ]
